In [1]:
import pandas as pd

In [34]:
college_1257 = pd.read_csv('college.csv')

In [19]:
to_merge_6440 = pd.read_excel('nicole-klassen-level-1-university-admissions-data/University Directory Information with lables_2020.xlsx')
to_merge_6440.shape

(6440, 50)

In [21]:
to_merge_1989 = pd.read_excel('nicole-klassen-level-1-university-admissions-data/University Admissions with lables_2020.xlsx')
to_merge_1989.shape

(1989, 39)

In [29]:
college_1557 = pd.read_csv('Data-Table 1.csv')

In [26]:
merged = to_merge_6440.merge(to_merge_1989, on ='Unique identification number of the institution')

In [30]:
merged = merged.merge(college_1557, right_on='Name', left_on='Institution (entity) name')

In [36]:
merged = merged.merge(college_1257, right_on='Name', left_on='Institution (entity) name')

In [37]:
merged

,Unique identification number of the institution,Institution (entity) name,Institution name alias,Street address or post office box,City location of institution,State abbreviation_x,ZIP code,Bureau of Economic Analysis (BEA) regions,Name of chief administrator,Title of chief administrator,...,AdmissionRate,ACTMedian,SATAverage,AverageCost,Expenditure,AverageFacultySalary,MedianDebt,AverageAgeofEntry,MedianFamilyIncome,MedianEarnings
0,100654,Alabama A & M University,AAMU,4900 Meridian Street,Normal,AL,35762,"Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC,...","Dr. Andrew Hugine, Jr.",President,...,0.8989,17,823,18888,7459,7079,19500.0,20.629999,29039.0,27000
1,100663,University of Alabama at Birmingham,NaN,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,"Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC,...",Ray L. Watts,President,...,0.8673,25,1146,19990,17208,10170,16250.0,22.670000,34909.0,37200
2,100706,University of Alabama in Huntsville,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,"Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC,...",Darren Dawson,President,...,0.8062,26,1180,20306,9352,9341,16500.0,23.190001,39766.0,41500
3,100724,Alabama State University,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,"Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC,...",Quinton T. Ross,President,...,0.5125,17,830,17400,7393,6557,15854.5,20.889999,24029.5,22400
4,100751,The University of Alabama,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,"Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC,...",Dr. Stuart R. Bell,President,...,0.5655,26,1171,26717,9817,9605,17750.0,20.770000,58976.0,39200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128,409698,California State University-Monterey Bay,CSUMB,100 Campus Center,Seaside,CA,93955-8001,"Far West (AK, CA, HI, NV, OR, WA)",Eduardo M. Ochoa,President,...,0.4440,21,976,18479,8677,7478,13750.0,24.190001,38387.0,37100
1129,433660,Florida Gulf Coast University,NaN,10501 Fgcu Blvd S,Fort Myers,FL,33965-6565,"Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC,...",Dr. Michael Martin,President,...,0.6579,22,1024,18097,6606,7382,11625.0,22.430000,46981.0,37600
1130,441937,California State University-Channel Islands,CSU Channel Islands,One University Dr,Camarillo,CA,93012,"Far West (AK, CA, HI, NV, OR, WA)",Richard Yao,Interim President,...,0.6443,20,954,22570,12026,8434,12500.0,24.850000,32103.0,35800
1131,486840,Kennesaw State University,KSU,1000 Chastain Rd,Kennesaw,GA,30144,"Southeast (AL, AR, FL, GA, KY, LA, MS, NC, SC,...",Pamela Whitten,President,...,0.5654,23,1068,20630,6179,6252,15000.0,24.510000,41150.5,37200
1132,487524,Husson University,Husson,1 College Circle,Bangor,ME,04401-2929,"New England (CT, ME, MA, NH, RI, VT)",Robert A. Clark,President,...,0.7989,19,962,25019,6274,6539,21329.0,22.200001,46670.0,34600